### PR TITLE
test with real user, with updated config file in master

### PR DESCRIPTION
**Pull request by tommy-meacham**

### CODE REVIEW

**Comment by ondrej-kocan-ct** [comment]
☯️

**Comment by tommy-meacham** [comment]
woop! it works with groups

**Comment by ondrej-kocan-ct** [comment]
Is it possible to name the groups? Would it break anything?

**Comment by tommy-meacham** [comment]
In the config file you mean?

**Comment by ondrej-kocan-ct** [comment]
Yes

**Comment by tommy-meacham** [comment]
Will have a look. I guess its just a case of "will yaml allow it".

**Comment by ondrej-kocan-ct** [comment]
it should. I don't think there's any way we could leverage having the names in there.

**Pull request merged**
